services:
  web:
    build: .
    container_name: smarthands_web
    env_file:
      - .env.production     # secrets de prod ici (pas de NEXT_PUBLIC_ pour les secrets)
    expose:
      - "3000"              # exposé seulement au réseau interne
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: smarthands_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

